name: Django CI

on:
  push:
    branches: [ "feature/**" ]
  pull_request:
    branches: [ "feature/**" ]
    
  workflow_dispatch:

jobs:
  build:

    runs-on: [ "AWSEC2test" ]
    strategy:
      matrix:
        python-version: [ "3.10" ]

    steps:
    - name: pull commits
      uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        
    - name: Django Migration
      run: |
        cd app
        python3 manage.py makemigrations
        python3 manage.py migrate
        #python3 manage.py collectstatic

    - name: Run App Server
      run: |
        cd app
        ls
        python3 manage.py runserver 0.0.0.0:8000
        
