name: Django CI

on:
  push:
    branches: [ "feature/**" ]
  pull_request:
    branches: [ "feature/**"  ]

  workflow_dispatch:

jobs:
  Analysis:

    runs-on: [self-hosted, linux, X64]
    
    steps:
    - name: Take new version 
      uses: actions/checkout@v3
    
    - name: Analyze with SonarQube
      run: |
        sonar-scanner
      
