name: Django CI

on:
  push:
    branches: [ "feature/**" ]
  pull_request:
    branches: [ "feature/**"  ]

  workflow_dispatch:

jobs:
  Analysis:
    runs-on: ["self-hosted", "linux", "X64"]
    
    steps:
    - name: Take code for analyze 
      uses: actions/checkout@v3
      
    - name: Analyze with SonarQube
      shell: bash
      env:
        login: ${{ secrets.UBUNTU_SS_LOGIN }}
      run: |
        sonar-scanner \
        -Dsonar.projectKey=local-analyze \
        -Dsonar.sources=. \
        -Dsonar.host.url=http://localhost:9000 \
        -Dsonar.login="$login"
    
