name: Django CI

on:
  push:
    branches: [ "feature/**" ]
  pull_request:
    branches: [ "feature/**"  ]

  workflow_dispatch:

jobs:
  build:

    runs-on: [self-hosted,  Windows, X64]
    strategy:
      matrix:
        python-version: [ "3.10" ]

    steps:
    - name: Take new version 
      uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Check Directory
      uses: |
        ls 
        ls app
        
#    - name: Install Dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install -r requirements.txt

#    - name: Run App Server
#      run: |
#        cd app
#        python manage.py runserver 0.0.0.0:8000
