name: Django CICD for dev server

on:
  push:
    branches-ignore: [ "main", "production" ]
  pull_request:
    branches: [ "main" ]
    types:
      - closed
  workflow_dispatch:

jobs:
  deploy-to-dev:
    if: ${{ github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch' }}

    runs-on: ubuntu-latest
    steps:
    - name: echo 
      run: |
        echo A pull request was closed
