
name: Django CI

on:
  push:
    branches-ignore: [ "main", "production" ]
  pull_request:
    branches: [ "main" ]
    types:
      - closed
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch' }} 
    run: |
      echo A pull request was closed
   
